### ISSUE TITLE
[FEATURE] Custom settings in securedBy

### ISSUE THREAD

**Issue by rickmacgillis** [raml-org/raml-php-parser#71]
The official RAML specs [state](http://raml.org/spec.html#usage-applying-a-security-scheme-to-an-api) that the securedBy field can specify custom settings for the security scheme. The syntax shown on the official documentation is incompatable with the Symfony YAML parser, but an alternative syntax makes the custom settings possible.

**Official syntax**

`securedBy: [null, oauth_2_0: { scopes: [ ADMINISTRATOR ] } ]`

**Compatable Syntax**

`securedBy: [null, {oauth_2_0: { scopes: [ADMINISTRATOR] } } ]`

**Update notes**

The only difference in the alternative syntax is that you make each parameter receiving alternate values an array. My update adds the custom settings functionality for the resource and method securedBy parameters, but doesn't alter references when you use securedBy at the root. (Just set those settings in the security schemes as the defaults.)

I've also added a couple extra features to make it easier to work with security schema settings objects. In addition to the existing functionality to add settings for RAML specified entries, you can now add custom settings for your authentication methods. Call `getSettings()` on the settings object to grab an array of all settings data. The parsers now use the createFromArray() method to populate data.

**Comment by alecsammon** [comment]
So - thinking about this ticket in more depth.

I think changing the schema is a bad approach. It would break interoperability between this library, and other libraries. 

It is a bug in the syfony yaml parser - I'm trying to see how easy it is to make a fix and put in a pull request.

Until then using the following syntax is identical - however is supported by the library. It is a little bit more verbose, however I don't think it's more difficult to read

{code}
securedBy:
      - null
      - oauth_2_0: {scopes: [ADMINISTRATOR]}
{code}
